Repository rider577/web-dev-projects, pull requests merged in 2022-10, with the labels that each got.

#3 adding `javascript` to calculator
  calculatorX/app.js
Labels: hacktoberfest, hacktoberfest-accepted

#6 updated the whole application
  calculatorX/app.js
  calculatorX/index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 Create README.md
  calculatorX/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#10 added style to visualizer
  visualizer/index.html
  visualizer/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 tweaks to `calculator`
  calculatorX/app.js
  calculatorX/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 added javascript
  visualizer/script.js
Labels: hacktoberfest, hacktoberfest-accepted
